force-app/main/default/objects/Account/fields/ABID__c.field-meta.xml
<CustomField>
    <fullName>ABID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Acme Bank Unique ID (ABID).</description>
    <externalId>true</externalId>
    <inlineHelpText>Acme Bank Unique ID (ABID).</inlineHelpText>
    <label>ABID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{0000000}</displayFormat>
        <label>Financial Account</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spending</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balance_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Balance Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Financial_accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinancialTransaction__c/FinancialTransaction__c.object-meta.xml
<CustomObject>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Financial Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialTransaction__c/fields/Currency_Type__c.field-meta.xml
<CustomField>
    <fullName>Currency_Type__c</fullName>
    <label>Currency Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialTransaction__c/fields/FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccount__c</fullName>
    <label>Financial Account</label>
    <referenceTo>FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Transactions</relationshipLabel>
    <relationshipName>Financial_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinancialTransaction__c/fields/Merchant_ABN__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ABN__c</fullName>
    <label>Merchant ABN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialTransaction__c/fields/MerchantBSB__c.field-meta.xml
<CustomField>
    <fullName>MerchantBSB__c</fullName>
    <label>Merchant BSB</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialTransaction__c/fields/MerchantName__c.field-meta.xml
<CustomField>
    <fullName>MerchantName__c</fullName>
    <label>Merchant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialTransaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>credit</fullName>
            </value>
            <value>
                <fullName>debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ACME_FInancialTransactionServiceTest.cls
@isTest
private class ACME_FInancialTransactionServiceTest {
    @testSetUp
    static void setup() {
        Profile readOnlyProfile = [SELECT Id FROM Profile WHERE Name = 'Read Only'];
        
        User testUser = new User(FirstName = 'Test',
                                    LastName = 'user',
                                    Email = 'testuser@email.com',
                                    Username = 'testuser@email.com'+ '.' + Math.random(),
                                    Alias = 'tuser',
                                    ProfileId = readOnlyProfile.Id,
                                    TimeZoneSidKey = 'Australia/Sydney',
                                    LocaleSidKey = 'en_US',
                                    EmailEncodingKey = 'ISO-8859-1',
                                    LanguageLocaleKey = 'en_US');
        insert testUser;

        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'ACME'];
        insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps.Id);
    }
    private static User getTestRunUser(){
        return [SELECT Id FROM User WHERE Email = 'testuser@email.com'];
    }

    @isTest
    static void testPost1(){
        System.runAs(getTestRunUser()) {
            
            Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(System.Label.PersonAccountRT).getRecordTypeId();
            Account persAcc = new Account();
            persAcc.RecordTypeId = personAccountRecordTypeId;
            persAcc.FirstName = 'John';
            persAcc.LastName = 'Doe';
            persAcc.PersonEmail = 'test14@test14.com';
            insert persAcc;

            FinancialAccount__c finAcc = new FinancialAccount__c();
            finAcc.AccountType__c = 'Spending';
            finAcc.Customer__c = persAcc.Id;
            insert finAcc;
            
            List<FinancialAccount__c> finaccList = [SELECT Id, Balance_Amount__c, Customer__r.ABID__c,Account_Number__c FROM FinancialAccount__c LIMIT 1];

            Time currentTime =  Time.newInstance(3, 14, 15, 926);
            List<FinancialTransaction__c> finTrans = new List<FinancialTransaction__c>();
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 300,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-30), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'credit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 100,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-25), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 50,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-20), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 100,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-17), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'credit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 75,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-10), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            insert finTrans;
            
            String jsonStr= '{ "abid": "'+ finaccList[0].Customer__r.ABID__c + '", "accountNumber": ' + Long.Valueof(finaccList[0].Account_Number__c)+ ', "amount": 125.68, "currency": "AUD", "date": "2020/01/01", "merchantABN": 123456789, "merchantBSB": 123456, "merchantName": "Beau Flowers", "time": "17:32:25", "type": "" }';
            Test.startTest();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();             
            req.requestURI = '/services/apexrest/accounttransaction/';
            req.httpMethod = 'POST';
            RestContext.request = req;
            RestContext.response= res;
            req.requestBody = BLOB.ValueOf(jsonStr);

            ACME_FInancialTransactionService.doPost();
            Test.stopTest();
        }

        List<FinancialAccount__c> finaccList2 = [SELECT Id, Balance_Amount__c FROM FinancialAccount__c LIMIT 1];
        System.assertEquals( finaccList2[0].Balance_Amount__c, 175, 'Account balance is not calculated');
    }
    @isTest
    static void testPost2(){
        System.runAs(getTestRunUser()) {
            
            Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(System.Label.PersonAccountRT).getRecordTypeId();
            Account persAcc = new Account();
            persAcc.RecordTypeId = personAccountRecordTypeId;
            persAcc.FirstName = 'John';
            persAcc.LastName = 'Doe';
            persAcc.PersonEmail = 'test14@test14.com';
            insert persAcc;

            FinancialAccount__c finAcc = new FinancialAccount__c();
            finAcc.AccountType__c = 'Spending';
            finAcc.Customer__c = persAcc.Id;
            insert finAcc;
            
            List<FinancialAccount__c> finaccList = [SELECT Id, Balance_Amount__c, Customer__r.ABID__c,Account_Number__c FROM FinancialAccount__c LIMIT 1];

            Time currentTime =  Time.newInstance(3, 14, 15, 926);

            List<FinancialTransaction__c> finTrans = new List<FinancialTransaction__c>();
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 300,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-30), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'credit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 100,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-25), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 50,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-20), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 100,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-17), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'credit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 75,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-10), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            insert finTrans;
            
            String jsonStr= '{ "abid": "176214376", "accountNumber": ' + Long.Valueof(finaccList[0].Account_Number__c)+ ', "amount": 125.68, "currency": "AUD", "date": "2020/01/01", "merchantABN": 123456789, "merchantBSB": 123456, "merchantName": "Beau Flowers", "time": "17:32:25", "type": "debit" }';
            Test.startTest();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();             
            req.requestURI = '/services/apexrest/accounttransaction/';
            req.httpMethod = 'POST';
            RestContext.request = req;
            RestContext.response= res;
            req.requestBody = BLOB.ValueOf(jsonStr);

            ACME_FInancialTransactionService.doPost();
            Test.stopTest();
        }

        List<FinancialAccount__c> finaccList2 = [SELECT Id, Balance_Amount__c FROM FinancialAccount__c LIMIT 1];
        System.assertEquals( finaccList2[0].Balance_Amount__c, 175, 'Account balance is not calculated');
    }
    @isTest
    static void testPost3(){
        System.runAs(getTestRunUser()) {
            
            Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(System.Label.PersonAccountRT).getRecordTypeId();
            Account persAcc = new Account();
            persAcc.RecordTypeId = personAccountRecordTypeId;
            persAcc.FirstName = 'John';
            persAcc.LastName = 'Doe';
            persAcc.PersonEmail = 'test14@test14.com';
            insert persAcc;

            FinancialAccount__c finAcc = new FinancialAccount__c();
            finAcc.AccountType__c = 'Spending';
            finAcc.Customer__c = persAcc.Id;
            insert finAcc;
            
            List<FinancialAccount__c> finaccList = [SELECT Id, Balance_Amount__c, Customer__r.ABID__c,Account_Number__c FROM FinancialAccount__c LIMIT 1];

            Time currentTime =  Time.newInstance(3, 14, 15, 926);
            List<FinancialTransaction__c> finTrans = new List<FinancialTransaction__c>();
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 300,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-30), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'credit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 100,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-25), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 50,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-20), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 100,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-17), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'credit'));
            finTrans.add(new FinancialTransaction__c(FinancialAccount__c = finAcc.Id, Amount__c = 75,Currency_Type__c = 'AUD', Date__c = System.today().addDays(-10), MerchantBSB__c = '123456',MerchantName__c = 'test food court',
                                                Merchant_ABN__c = '123456789',Time__c = currentTime,Type__c = 'debit'));
            insert finTrans;
            
            String jsonStr= '{ "abid": "'+ finaccList[0].Customer__r.ABID__c + '", "accountNumber": ' + Long.Valueof(finaccList[0].Account_Number__c)+ ', "amount": 125.68, "currency": "AUD", "date": "2020/01/01", "merchantABN": 123456789, "merchantBSB": 123456, "merchantName": "Beau Flowers", "time": "17:32:25", "type": "credit" }';
            Test.startTest();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();             
            req.requestURI = '/services/apexrest/accounttransaction/';
            req.httpMethod = 'POST';
            RestContext.request = req;
            RestContext.response= res;
            req.requestBody = BLOB.ValueOf(jsonStr);

            ACME_FInancialTransactionService.doPost();
            ACME_FInancialTransactionService.doPost();
            ACME_FInancialTransactionService.doPost();
            ACME_FInancialTransactionService.doPost();
            ACME_FInancialTransactionService.doPost();
            ACME_FInancialTransactionService.doPost();
            Test.stopTest();
        }

        List<FinancialAccount__c> finaccList2 = [SELECT Id, Balance_Amount__c FROM FinancialAccount__c LIMIT 1];
        System.assertEquals( finaccList2[0].Balance_Amount__c, 300.68, 'Account balance is not calculated');
    }
}