force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{0000000}</displayFormat>
        <label>Financial Account</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spending</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Financial_accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ACME_FinancialAccountTriggerHandlerTest.cls
@isTest
private class ACME_FinancialAccountTriggerHandlerTest {
    @testSetUp
    static void setup() {
        Profile readOnlyProfile = [SELECT Id FROM Profile WHERE Name = 'Read Only'];
        
        User testUser = new User(FirstName = 'Test',
                                    LastName = 'user',
                                    Email = 'testuser@email.com',
                                    Username = 'testuser@email.com'+ '.' + Math.random(),
                                    Alias = 'tuser',
                                    ProfileId = readOnlyProfile.Id,
                                    TimeZoneSidKey = 'Australia/Sydney',
                                    LocaleSidKey = 'en_US',
                                    EmailEncodingKey = 'ISO-8859-1',
                                    LanguageLocaleKey = 'en_US');
        insert testUser;

        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'ACME'];
        insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps.Id);
    }
    private static User getTestRunUser(){
        return [SELECT Id FROM User WHERE Email = 'testuser@email.com'];
    }

    @isTest
    static void testFinancialAccountCreate(){
        System.runAs(getTestRunUser()) {
            
            Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(System.Label.PersonAccountRT).getRecordTypeId();
            Account persAcc = new Account();
            persAcc.RecordTypeId = personAccountRecordTypeId;
            persAcc.FirstName = 'John';
            persAcc.LastName = 'Doe';
            persAcc.PersonEmail = 'test14@test14.com';
            insert persAcc;

            Test.startTest();

            FinancialAccount__c finAcc = new FinancialAccount__c();
            finAcc.AccountType__c = 'Spending';
            finAcc.Customer__c = persAcc.Id;
            insert finAcc;
            
            Test.stopTest();
        }

        List<FinancialAccount__c> finaccList = [SELECT Id, Account_Number__c FROM FinancialAccount__c LIMIT 1];

        System.assert( String.isNotBlank(finaccList[0].Account_Number__c), 'Account Number is not populated.');
    }
}